// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvmuotlxxdsfgvgbiwhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2bXVvdGx4eGRzZmd2Z2Jpd2htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODEzOTksImV4cCI6MjA1ODc1NzM5OX0.EWB9SS1Me2jaKkk4fU2ocU2x_OijSD6BN6tuJPHQ6sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);